### ISSUE TITLE
Dynatrace Agent Not Detecting Communication Endpoints and Tenant Information

### ISSUE THREAD

**Issue by vuhp** [paketo-buildpacks/dynatrace#75]
## Expected Behavior
The agent should be capable of correctly identifying communication endpoints, along with the tenant ID and tenant token.

## Current Behavior
Currently, the Dynatrace agent is not utilizing (or not using at all) the data retrieved from the connectioninfo API to appropriately configure the token, tenant ID, and communication endpoints for establishing a connection with the Dynatrace backend.

Although the connectioninfo API provides all the required details, such as the token, tenant ID, and communication endpoint, the agent is not utilizing this data to set up the connection parameters. Instead, it defaults to attempting to connect to http://localhost:8020/communication for communication, which results in unsuccessful connections.

This behavior contradicts the intended functionality, where the agent should be able to autonomously configure itself using the information from the connectioninfo API.

## Possible Solution
At this point, a potential solution has not been identified. It's essential to further investigate the agent's handling of the connectioninfo data and how it processes the token, tenant ID, and communication endpoint details. 
Or does it make the call to connectioninfo API at all?

## Steps to Reproduce
1. Set up a Spring Boot application.
2. Add the necessary bindings for Dynatrace configuration.
3. Build an image from the application created in step 1.
4. Run the resulting image.

## Motivations
We have a strong motivation to adopt the Dynatrace buildpack to enhance our application's startup time. The current Dynatrace operator adds a significant delay due to its injection of an init container for agent download. By utilizing the buildpack, we aim to mitigate this added delay and streamline our startup process.

**Comment by dmikusa** [comment]
> Currently, the Dynatrace agent is not utilizing (or not using at all) the data retrieved from the connectioninfo API to appropriately configure the token, tenant ID, and communication endpoints for establishing a connection with the Dynatrace backend.

Can you expand on this? The buildpacks team is not experts on all the software we integrate, it's just far too much stuff. If you can provide more details on how this works in Dynatrace, we can likely point you in the right direction or get some code changes to help.

A good way to do this is to explain how you'd normally do this on a VM or with Dockerfiles. Be as specific as possible. We can usually then translate to how it should work with buildpacks.

Thanks

**Comment by vuhp** [comment]
Actually I just found this logic in this code repo here: https://github.com/paketo-buildpacks/dynatrace/blob/1f8c8cf74b1d7266b32330055201094f0881148c/helper/properties.go#L60-L92

Somehow it doesn’t work as expected, i.e. the env vars are not set to the values returned from `/v1/deployment/installer/agent/connectioninfo`.

It’s a bit hard to explain if you’re not familiar with Dynatrace. But I hope the above code snippet can give you some idea.

**Comment by dmikusa** [comment]
Gotcha, thanks. I'm on the same page now.

So this code runs in what we call a helper (the buildpack spec calls them exec.d binaries). The helpers/exec.d binaries run prior to your application starting in the launch or runtime container. The main purpose is to do things like this and configure the environment in which your application code will ultimately run.

A couple of things can commonly go wrong here:

1. Are you also setting your bindings at launch/runtime? Bindings for DT need to be set both when you build and when you run your application image. If the bindings are not set, then the helper won't run.

2. Which brings us to the next question. Can you confirm that the helper runs? Do you see the line `Configuring Dynatrace properties` when you start your app image? It should run if you've set bindings, but if it's not running that could signal something isn't right or expected with the bindings.

3. The info we get back from the connect info request get's set in env variables. It would be good to peek and see what those are being set to. It would be helpful to [override the start process](https://buildpacks.io/docs/app-developer-guide/run-an-app/#user-provided-shell-process) and execute `env` instead. That will dump the env variables as set by the buildpack and helper. You can then see the tenant, token and connection point being set. That'll help understand more about what is going on here.

Hope that helps.

**Comment by vuhp** [comment]
Indeed, the helper wasn't executed due to the absence of bindings at runtime. I had initially assumed that the bindings were only necessary during the build time.

It might be beneficial for the instructions in the readme to provide more clarity on this aspect.

I appreciate your explanation. Thank you.

**Comment by vuhp** [comment]
Another observation: When I omit runtime bindings for ca-certificates, the helper encounters difficulties using buildtime-provided certificates to connect to `/v1/deployment/installer/agent/connectioninfo`, due to our private CA. 

Strangely, our Spring Boot app successfully utilizes these buildtime CA certs, which contrasts with the behavior of the dynatrace buildpack helper. Is this intended?

**Comment by dmikusa** [comment]
Glad that helped!

> It might be beneficial for the instructions in the readme to provide more clarity on this aspect.

Good feedback. I'll add a story to improve our docs. Thanks

> Strangely, our Spring Boot app successfully utilizes these buildtime CA certs, which contrasts with the behavior of the dynatrace buildpack helper. Is this intended?

Hmm, it could be a difference in the system CA certs vs the Java CA certs. The JVM keeps its own keystore with trusted certs, where the Helpers are written in Go and utilize the OpenSSL system CA certs. I'd have to see the output of build & run. The bindings can will add the certs at build time but that's only for build time (unless you use the option to embed the CA certs). If you omit them at runtime, I'd expect them to not be available. There's a lot of variables though.

Pro tip: for trusted certs, using the `BP_EMBED_CERTS` is really convenient. It'll take the ca-certificates bindings at build time and embed them into the image so you don't need the bindings at runtime. Since trusted certs are just public keys and not secret, it is safe to embed them. The only reason you may not want to do this would be if your trusted certs change often & you want to be able to update them without needing to rebuild the image.

Hope that helps!

**Comment by vuhp** [comment]
Thank you for the suggestion regarding `BP_EMBED_CERTS`, it has resolved my issue.

Nonetheless, it appears that the behavior of importing the certificates to the JVM trust store and the ability of Spring to utilize build-time certificates might not have been intentionally designed. I've checked various documents from both buildpacks and Paketo, but I haven't come across any documentation covering this aspect.

**Comment by dmikusa** [comment]
> @dmikusa shouldn't the bindings at build time be used again at run time by default, unless specifically overridden by runtime bindings?

No. That's the purpose of bindings. They contain *secret* information so it cannot be included into the container information, or you'll leak the secrets. That is why you need to specify them at both build and runtime in this case.

Having said that, there are some bindings that only apply at build time or only at runtime. If that's the case, then you only need them during the given phase of the lifecycle. In this case, with Dynatrace, they're needed at build time to trigger the agent to be installed and at runtime to actually configure the agent.
